### ISSUE TITLE
Name displays as ?????? and doesn't save edits.

### ISSUE THREAD

**Issue by lolcatplays** [AdmiralCurtiss/OoTSaveEditor#4]
I can attach my file here if you can change the name back to Link for me that'd be nice

**Comment by AdmiralCurtiss** [comment]
Yeah name editing wasn't supported. I added it, is this what you want?

[THE LEGEND OF ZELDA.zip](https://github.com/AdmiralCurtiss/OoTSaveEditor/files/5562746/THE.LEGEND.OF.ZELDA.zip)

**Comment by lolcatplays** [comment]
> Yeah name editing wasn't supported. I added it, is this what you want?
> 
> [THE LEGEND OF ZELDA.zip](https://github.com/AdmiralCurtiss/OoTSaveEditor/files/5562746/THE.LEGEND.OF.ZELDA.zip)

Thanks man!
